/*
 * CardDetailsEditor.java
 *
 * Created on July 4, 2004, 11:36 AM
 */

package robowars.editor.typepanels;

import java.sql.*;
import java.util.Map;

/**
 *
 * @author  bdickie
 */
public abstract class CardDetailsEditor extends javax.swing.JPanel {
    
    /** Creates new form CardDetailsEditor */
    public CardDetailsEditor() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        
        setLayout(new java.awt.BorderLayout());
        
    }//GEN-END:initComponents
    
    
    public abstract void loadDetails(ResultSet rs) throws SQLException;
    public abstract boolean saveDetails(Map values);
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    
}
