/*
 * PlanetEditPanel.java
 *
 * Created on July 4, 2004, 11:38 AM
 */

package robowars.editor.typepanels;


/**
 *
 * @author  bdickie
 */
public class PlanetEditPanel extends CardDetailsEditor {
    
    /** Creates new form PlanetEditPanel */
    public PlanetEditPanel() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jLabel1 = new javax.swing.JLabel();
        txtAttackRoom = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtDefenderRoom = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtFacilityRoom = new javax.swing.JTextField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Attacker Room:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 110, -1));

        add(txtAttackRoom, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 70, -1));

        jLabel2.setText("Defender Room:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 100, -1));

        add(txtDefenderRoom, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 70, -1));

        jLabel3.setText("Facility Room:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 100, -1));

        add(txtFacilityRoom, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 70, -1));

    }//GEN-END:initComponents

    public void loadDetails(java.sql.ResultSet rs) throws java.sql.SQLException {
        txtAttackRoom.setText(rs.getString("card_attack_space"));
        txtDefenderRoom.setText(rs.getString("card_defend_space"));
        txtFacilityRoom.setText(rs.getString("card_facility_space"));
    }    
    
    public boolean saveDetails(java.util.Map values) {
        values.put("card_attack_space", txtAttackRoom.getText());
        values.put("card_defend_space", txtDefenderRoom.getText());
        values.put("card_facility_space", txtFacilityRoom.getText());
        return true;
    }    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtAttackRoom;
    private javax.swing.JTextField txtDefenderRoom;
    private javax.swing.JTextField txtFacilityRoom;
    // End of variables declaration//GEN-END:variables
    
}
